### ISSUE TITLE
Content review email notifications

### ISSUE THREAD

**Issue by Brighty28** [umbraco/Umbraco.Workflow.Issues#17] opened 2023-05-19 21:45 UTC
I installed a fresh copy of Umbraco workflow 10.2.0 and it's primarily working just I can't seem to get email notifications to send when the content review is about to expire can you please advise? I have also mentioned this on the Umbraco forum https://our.umbraco.com/packages/backoffice-extensions/plumber-workflow-for-umbraco/plumber-workflow-for-umbraco-discussion-and-troubleshooting/109537-plumber-v10#comment-339721

I have set media to expire and updated the default notification setting, but the email notifications are not coming through and I get the below error in the Umbraco logs
![IMG_4383](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/6204366/53fc3eed-b113-4dcb-bbd8-d69ee99709cd)

**Comment by nathanwoulfe** [comment] 2023-05-22 00:12
Hey @Brighty28 @BradleyCSO, thanks for the report - I've found the cause and will have this fixed in the next patch release for 10 and 11. Hadn't planned a date for that, but thinking next week would be sensible.

**Closed** 2023-05-30 08:23 UTC
Labels: type/bug, release/11.2.1, release/10.2.1
