### ISSUE TITLE
Vendr Settings node being overwritten when Umbraco.Workflow is installed

### ISSUE THREAD

**Issue by tony-gledhill** [umbraco/Umbraco.Workflow.Issues#11] opened 2023-02-28 12:41 UTC
Vendr: 3.0.5
Umbraco.Workflow: 10.0.0
Umbraco.CMS: 10.3.2

Installing Umbraco.Workflow into Umbraco that already has an instance of Vendr installed, causes the Vendr settings node in the admin panel to be overwritten with the Umbraco.Workflow settings node.

This means that we are unable to update the settings in Vendr

![221847882-26d6a974-2b20-450b-86f4-1c99c0c830b9](https://user-images.githubusercontent.com/87007134/221856830-088164bf-29f5-450d-ab7b-510d2f27315a.png)

**Comment by nathanwoulfe** [comment] 2023-02-28 22:44
Hey @tony-gledhill that's a wild one! Will look into it, should be able to include the fix in the 10.1/11.1 releases next week.

**Comment by nathanwoulfe** [comment] 2023-02-28 23:31
Interesting one this is... Looks like the issue is caused by both products including a TreeController class named `SettingsTreeController`, which causes confusion somewhere in Umbraco when rendering the trees. There's nothing I can see in the returned tree data (from the request to `/umbraco/backoffice/umbracotrees/applicationtree/GetApplicationTrees?application=settings&tree=&use=main`), but somewhere in the pipeline the Workflow tree is replacing the Vender tree.

If I rename my class to `WorkflowSettingsTreeController` the issue is gone, both trees work as expected.

Would be good to know why, but for now, I can include the fix in the 10.1/11.1 releases

**Comment by nathanwoulfe** [comment] 2023-03-09 23:15
Resolved in 10.1/11.1 releases 🚀

**Closed by nathanwoulfe** 2023-03-09 23:15 UTC
Labels: type/bug, release/11.1.0
