### ISSUE TITLE
Should not allow to initiate workflow when no workflow is configured

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#1] opened 2022-11-15 08:39 UTC
A brief description of the issue goes here.

There is no workflow set on the document type and when I try to request publish it throws an error.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Specifics

Using Umbraco CMS version 11.0.0-rc4, Workflow v11.0.0-rc2
![Initiate_Workflow_Error](https://user-images.githubusercontent.com/82437098/201872521-55de9281-e6c0-49d3-a914-0a5662fa5ad1.png)

### Steps to reproduce

 1. Do not set a content approval flow in the Configuration section of the Workflow content app.
  2. Edit a property in the content node.
  3. Request for publish
  4. Throws an error.
  5. Add a content approval flow in the Configuration section of the Workflow content app.
  6. Save it
  7. Request for publish.
  8. Still throws an error

### Expected result

Either should not allow to initiate a workflow or throw a friendly error message as to what should be done to initiate a workflow succesfully.

### Actual result

https://user-images.githubusercontent.com/82437098/201871971-242925b0-6216-4072-9fd7-8864be4615f9.mp4

**Comment by nathanwoulfe** [comment] 2022-11-17 01:41
Hey @eshanrnh, did you by chance have a previous Workflow/Plumber version installed on this site? Might be worth checking there's no Plumber folder in App_Plugins...

I'm trying to reproduce locally, but when I visit the content app on a node with no config, I don't get the Active workflow tab at all:
![image](https://user-images.githubusercontent.com/3248070/202333120-8100cb3d-37d0-4c01-83da-5863db2eed7e.png)

**Comment by eshanrnh** [comment] 2022-11-17 08:12
Hey @nathanwoulfe No, it was a fresh Workflow installation on a fresh CMS install. I checked the App_Plugins and there is no Plumber folder in it. Also, if it helps I had no Settings enabled in the Workflow Settings section.

**Comment by nathanwoulfe** [comment] 2022-11-28 05:22
Heya @eshanrnh I've been trying, but can't reproduce this one - have installed the latest RC into a fresh Umbraco, no option to submit for workflow approval until the node has an approval flow configured...

**Comment by nathanwoulfe** [comment] 2022-12-07 00:09
Hi @eshanrnh I'm going to close this one - I can't reproduce. I've added some additional error handling to prevent the second part of your issue (attempting to submit after setting config was failing after the initial request failed).

If you're able to reproduce, do let me know!

**Closed by nathanwoulfe** 2022-12-07 00:09 UTC
Labels: release/11.0.0-rc3
