### ISSUE TITLE
Workflow "Settings" node gets overwritten by uSupport's "Settings" node

### ISSUE THREAD

**Issue by dalbard** [umbraco/Umbraco.Workflow.Issues#16] opened 2023-05-10 08:33 UTC
In my project where I have both Workflow and uSupport installed, Workflow's "Settings" node gets overwritten by uSupport's "Settings" node. In other words, the dashboard for uSupport's "Settings" is displayed instead of Workflow's "Settings" dashboard (see image below). 

![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/57010922/93b09b33-acb4-4d3a-a809-ed61b540f315)

This is quite similar to this issue #11, so it seems to be a variation of the same problem, even when using version 11.2.0 of Umbraco.Workflow. I'm not sure wether this is a Workflow issue or a uSupport issue, but nonetheless there seems to be some type of conflict in the TreeController.

### Specifics

    Where applicable:
    * Occurs in the Backoffice 
    * Using Umbraco.Workflow 11.2.0
    * Using Google Chrome 112.0.5615.140
    * Checked in Mozilla Firefox 110.0.1 and Microsoft Edge 113.0.1774.35, the issue still persists 
    * Not getting any errors regarding this, so bug fixing is somewhat ambiguous.

### Steps to reproduce

    * Start up an Umbraco project with the packages uSupport (version 1.2.1) and Umbraco.Workflow (11.2.0) installed.
    * Try to access the "Settings" node in the Workflow section. 

### Expected result

    * Expected to see the Workflow settings and to be able to configure these.
    
![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/57010922/91cbcebb-eeb4-446a-bbe0-10587a874a67)

### Actual result

    * Instead, uSupport's "Settings" dashboard is shown when clicking on Workflow's "Settings" node.

![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/57010922/93b09b33-acb4-4d3a-a809-ed61b540f315)

**Comment by nathanwoulfe** [comment] 2023-05-10 23:25
Hey @dalbard, thanks for the detailed description. I think you're right, this is similar to #11.

Will see if I can reproduce by installing uSupport, and will update here with my findings...

**Comment by nathanwoulfe** [comment] 2023-05-10 23:40
I'll close this as the issue is raised on the CMS tracker, and needs to be fixed in CMS rather than Workflow 👍

**Closed by nathanwoulfe** 2023-05-10 23:40 UTC
Labels: type/bug, release/11.2.1, release/10.2.1
