### ISSUE TITLE
Switching language in Umbraco removed the save and publish buttons

### ISSUE THREAD

**Issue by bb-michelle** [umbraco/Umbraco.Workflow.Issues#46] opened 2023-10-03 13:20 UTC
Hello, we are using Umbraco version 12.1.2 and Workflow version 12.1.1. 
When we switch language under the profile to Swedish instead of English (USA) we recieve an error message "Error: Unable to generate workflow scaffold" in red and all save, Save and Publish and Schedule buttons are gone. When refreshing the page the buttons appear again, but this keeps happening on all pages. Makes it impossible to work.

When switching language I do not expect workflow to stop working, and I do not expect my save and publish buttons to disappear :)

![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/146846448/19e978f2-d45f-4030-8e49-82f7c854e1aa)

**Comment by nathanwoulfe** [comment] 2023-10-03 21:50
Hi @bb-michelle, that's strange - we fixed the Swedish issue in a previous release so potentially this is a regression. I'll look into it.

**Comment by nathanwoulfe** [comment] 2023-10-03 21:58
I can't reproduce this on Workflow 12.1.1 - the original bug was reported in #44, and fixed in 12.1.0.

Are you able to provide more detailed reproduction steps?

**Comment by bb-michelle** [comment] 2023-10-04 07:03
Hello,
I can confirm that this is on workflow 12.1.1.

![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/146846448/4f57c18e-d0ef-4c1d-916c-a26040d373da)

When logged in, I click on my profile in the top right corner in Umbraco and click on "Edit".
Here I switch language to Swedish instead of English (USA). I then click back to the "Content" tab, and since I have switch language I am usually prompted to login again for the settings to activate. 

When I then click on any page in the left page tree I recieve the red error message in my original message. I can also no longer see my publish and save buttons, it is just white. When I refresh the page the buttons on that specific page do appear again, however if I click on a new page in the left page tree the same red message appear and the buttons are gone again.

**Comment by nathanwoulfe** [comment] 2023-10-06 05:53
Strange... I've tried again to replicate, but as far as I can see this exact issue was resolved in 12.1. I've tested with the different Swedish language variations, all work correctly.

Outside chance, but could you confirm that the site's project file references version 68.2.0.9 of `Microsoft.ICU.ICU4C.Runtime`

**Comment by nathanwoulfe** [comment] 2023-11-06 21:32
Hi @bb-michelle, any update on this one? I haven't been able to reproduce the issue.

**Comment by nathanwoulfe** [comment] 2023-11-27 22:03
Closing due to lack of activity. Happy to reopen if we have reproduction steps.

**Closed by nathanwoulfe** 2023-11-27 22:03 UTC
Labels: type/bug
