### ISSUE TITLE
Can't reach Umbraco installer with Umbraco Workflow installed

### ISSUE THREAD

**Issue by harry-gordon** [umbraco/Umbraco.Workflow.Issues#48] opened 2023-11-06 15:35 UTC
### Bug summary

- When `Umbraco.Workflow` is installed and I'm doing a fresh install (empty `umbracoDbDSN` value) I get an invalid operation exception with the error message: "The factory has not been configured with a proper connection string.".
- I suspect some part of Workflow isn't observing the runtime state and is requesting the database when it shouldn't!

### Reproduction steps

- Create a new Umbraco v10 project
- Install Workflow **v10.3.2**.
- Run the application
- You should see the exception on start-up 💥

---
_This item has been added to our backlog AB#34610_

**Comment by nathanwoulfe** [comment] 2023-11-06 21:31
Heya @harry-gordon... I thought you might be on the money with the runtime state, but this checked before running the upgrader/installer, so should not be the cause of this issue.

I'll need to have a closer look, but as a workaround for now, if you create the new project, run it, then install Workflow into the freshly-installed Umbraco instance, it will be all good. I'd like to move the Workflow installer to use package migrations too, really just for the additional visibility in the backoffice.

**Comment by nathanwoulfe** [comment] 2023-11-28 21:43
Hey @harry-gordon, fix for this was released yesterday as part of 10.3.3 and 12.2.0. Will also be included in 13.0.0 when that arrives in a couple of week's time 🚀

**Comment by harry-gordon** [comment] 2023-12-04 12:26
Thanks for the update @nathanwoulfe! I tried 10.3.3 on a couple of projects (our current project and a project I made to test the problem in isolation) and it still seems to be happening? I haven't tested 12/13.

**Comment by nathanwoulfe** [comment] 2023-12-04 22:57
That's a bit annoying, could be that the issue I thought I was fixing wasn't the actual cause. I'll revisit and see if I can reproduce.

**Comment by nathanwoulfe** [comment] 2023-12-04 23:02
Weird, I can reproduce it again - awesome too that the stack trace doesn't show anything related to Workflow. Time to start digging...

**Comment by nathanwoulfe** [comment] 2023-12-05 00:12
Hey @harry-gordon apologies for spamming updates, but I think this isn't directly a Workflow issue (still one for me to look at though).

Issue appears to be in Umbraco.Licenses, which attempts to write to the keyvalue table in an app started notification handler, which fails in a fresh Umbraco instance as we don't yet have a database to write to. The issue surfaces in Workflow due to the dependency on Umbraco.Licenses.

I'll get a fix into the licenses project and a patch out ASAP, but for now, the previously discussed solution will still work - initialise Umbraco with a database, then install Workflow.

**Comment by harry-gordon** [comment] 2023-12-05 13:25
Thanks for the update @nathanwoulfe! Yeah, it's not a helpful exception, there doesn't seem to be a great way to find out what requested the DB 🥲. Good luck! 🚀

**Comment by nathanwoulfe** [comment] 2023-12-08 08:33
Heya @harry-gordon, I've tracked this one down and squished it. Plan is for a patch for 10 and 12 to coincide with releasing 13 next week. I'm not entirely sure of the root-cause, other than it being related to repositories accessing SqlContext before the database was created (the confusing part being no code was executing other than building the DI container, so I'm still not sure what was actually attempting to access the SQL context). Made some constructor parameters lazy, and patched the licenses library, and it all looks to be ok.

Should be out mid-week next week.

**Comment by nathanwoulfe** [comment] 2023-12-14 22:34
And we are live - patches for 10 and 12 were released yesterday.

**Closed by nathanwoulfe** 2023-12-14 22:34 UTC
Labels: state/sprint-candidate, type/bug, release/10.3.3, release/12.2.0, release/13.0.0
