### ISSUE TITLE
Scheduling warning is shown, even though the publication time hasn't passed

### ISSUE THREAD

**Issue by sniffdk** [umbraco/Umbraco.Workflow.Issues#81] opened 2024-09-16 23:37 UTC
When looking at the "Active workflow" tab on a page with a publication date set, Umbraco will show a warning that the "Scheduled date passed before the workflow was completed." 

As you can see from the screenshot, that is not correct.

![image](https://github.com/user-attachments/assets/56269a13-8188-4482-b7bb-6ad4e9ae6e66)

Reproduction
------------

Seen on Umbraco 13.4.1 and Workflow 13.2.0+faab5a3

1. Request a publish at a specific time eg. 10 minutes ahead.
2. Go to the "Active workflow" tab.
3. See that the error is shown.

I realise that this is probably another display bug with timezones.

I've tested that the page is actually published at the correct time, and that seems to work as expected.
So this is a bug report for the wrongly displayed warning message.

---
_This item has been added to our backlog AB#44406_

**Comment by nathanwoulfe** [comment] 2024-09-27 05:40
@sniffdk I believe you're correct - timezones again. I'm not able to reproduce when running locally, and I fully expect that is due to the server time matching my local time. I think this should be resolved by getting the local date (via CMS' DateHelper), then comparing to the current JS Date, which will be local.

Will test on a Cloud site to confirm.

**Comment by nathanwoulfe** [comment] 2024-10-03 07:17
Patches out now, this one should be working correctly now 🚀

**Closed by nathanwoulfe** 2024-10-03 07:17 UTC
Labels: release/10.4.1, release/13.2.1, release/14.0.3
