### ISSUE TITLE
Workflow activity loading very slowly

### ISSUE THREAD

**Issue by mohukh175** [umbraco/Umbraco.Workflow.Issues#73] opened 2024-07-26 08:01 UTC
The workflow detail tab takes very long to load, sometimes up to 2 minutes.
![image](https://github.com/user-attachments/assets/c3bbd590-a3d3-4283-a338-ae64deb43d0e)

The site is using umbraco 10.8.6. We first noticed this issue after the workflow plugin's upgrade to 10.3.9. I've since upgraded the plugin locally and on a test site, and this issue occurs on both of them. It happens on the workflow detail tab on both, the Active Workflow and History pages.

**Reproduction**

- After requesting approval on a doctype, go to the umbraco workflow page in the backoffice.
- Go to Active Workflows.
- Click on the detail button for the workflow item.
- Go to History.
- Click on the detail button for the workflow item.

---
_This item has been added to our backlog AB#42671_

**Comment by nathanwoulfe** [comment] 2024-08-06 02:40
Hey @mohukh175 I haven't been able to replicate this one, nor have we had any other reports of similar issues. I'm wondering if it's actually a rendering issue rather than any slowness fetching data - could you check the network tab and confirm there are no long-running workflow-related requests?

It's possibly an AngularJs issue, where async functions don't always trigger a digest/repaint, so the UI appears to be lagging/hung. I'll try to find some time to look into it, but note that this version is out of support so should only be receiving security updates.

**Comment by mohukh175** [comment] 2024-08-19 14:43
Sorry for the delay in getting back to you on this, I was on leave and just saw your reply. The workflow requests complete fairly quickly, but the activity tab doesn't update for a while.
![image](https://github.com/user-attachments/assets/dc7df3ca-710b-40ae-8469-b012d03db791).
I'll once again try upgrading the plugin to the latest version and see if it resolves this issue, thanks.

**Comment by nathanwoulfe** [comment] 2024-08-20 23:00
Definitely looks like the issue I mentioned where async doesn't trigger a digest, so the UI hangs until the next cycle runs. I'll check in 13 too, if it's an issue there as well it's easier to justify patching the EOL version too.

**Comment by nathanwoulfe** [comment] 2024-09-03 04:59
@mohukh175 I haven't been able to reproduce this, but have made a change that will hopefully resolve it. Patch will be out in the next week or so, once I've dealt with other issues.

**Comment by mohukh175** [comment] 2024-09-03 07:15
That's great! Thanks a lot for your help on this.

**Comment by nathanwoulfe** [comment] 2024-09-15 22:32
Hi @mohukh175 this was resolved in the most recent versions, released last week.

**Closed by nathanwoulfe** 2024-09-15 22:32 UTC
Labels: release/10.4.0, release/13.2.0
